image: tutum/curl:latest

stages:
  - deploy

trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=$TRIGGER_TOKEN -F ref=$TRIGGER_REF_NAME https://gitlab.singularmentor.com.ar/api/v3/projects/81/trigger/builds"
