---
version: '2.0'
services:
  db:
    image: mysql:5.6
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: "ff4131c1a74f938adc1f1514a2a9f6677f527db5"
      MYSQL_DATABASE: "laslechuzas"
      MYSQL_USER: "laslechuzas"
      MYSQL_PASSWORD: "p3p4p111g#"
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306

  fpm:
    build: docker/fpm
    hostname: fpm
    environment:
      DB_NAME: "laslechuzas"
      DB_USER: "laslechuzas"
      DB_PASSWORD: "p3p4p111g#"
      DB_HOST: "db"
      WP_DEBUG: "true"
    volumes:
      - "./WordPress:/srv/laslechuzas/www/WordPress"
      - "./conf/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro"
      - "./conf/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini:ro"
    links:
      - db:db
  
  web:
    build: ./docker/web
    hostname: web
    volumes_from:
      - fpm
    ports:
      - "80:80"
    links:
      - fpm:fpm
